import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Activity,Clock3,Github,HeartPulse,Play,Radar as RadarIcon,Settings,ShieldCheck,UserRound,Wifi}from'lucide-react';import'./style.css';

type Zone={name:string;x:number;y:number;level:number};
const zones:Zone[]=[{name:'Présence',x:26,y:28,level:0},{name:'Mouvement',x:67,y:36,level:0},{name:'Respiration',x:55,y:68,level:0}];
function App(){const[presence,setPresence]=useState(false),[motion,setMotion]=useState(false),[scan,setScan]=useState(false),[confidence,setConfidence]=useState(18),[auto,setAuto]=useState(true),[history,setHistory]=useState<number[]>([18,20,17,21,26,23,25,28]);
 const run=()=>{if(scan)return;setScan(true);let n=0;const t=setInterval(()=>{n+=1;setConfidence(Math.min(96,18+n*7));if(n>=11){clearInterval(t);const present=Math.random()>.25;setPresence(present);setMotion(present&&Math.random()>.35);setConfidence(present?Math.floor(82+Math.random()*15):Math.floor(8+Math.random()*18));setHistory(h=>[...h.slice(-9),present?90:12]);setScan(false)}},160)};
 useEffect(()=>{if(!auto)return;const t=setInterval(run,30000);return()=>clearInterval(t)},[auto]);
 const status=presence?'HUMAIN DÉTECTÉ':'ZONE LIBRE';const graph=useMemo(()=>history.map((v,i)=>`${i*50},${120-v}`).join(' '),[history]);
 return <div className="app"><header><div className="brand"><div className="brandIcon"><Wifi/></div><div><h1>WiFi Sense</h1><p>Détection de présence par analyse du signal Wi‑Fi</p></div></div><nav><button className="active"><RadarIcon/>Radar</button><button><UserRound/>Présence</button><button><Clock3/>Historique</button><button><Settings/>Paramètres</button></nav><div className="status"><i/>{scan?'Analyse…':'Système actif'}<strong>CSI Sensing</strong></div></header>
 <div className="workspace"><aside className="left"><button className="scanBtn" onClick={run} disabled={scan}><Play fill="currentColor"/>{scan?'ANALYSE EN COURS':'LANCER L’ANALYSE'}</button><div className="switchRow"><span>Surveillance automatique</span><button className={'switch '+(auto?'on':'')} onClick={()=>setAuto(!auto)}><i/></button></div><div className="big"><b>{presence?'1':'0'}</b><span>personne estimée</span><HeartPulse/></div><div className="metric"><span>Confiance</span><strong>{confidence}%</strong><div className="bar"><i style={{width:confidence+'%'}}/></div></div><div className="metric"><span>État du mouvement</span><strong>{motion?'Mouvement':'Stable'}</strong></div><div className="network"><b><Wifi/> Liaison de sensing</b><p>Source<strong>Wi‑Fi CSI</strong></p><p>Mode<strong>Non-contact</strong></p><p>Dernière analyse<strong>à l’instant</strong></p></div><div className="menu"><a className="selected"><RadarIcon/>Vue radar</a><a><Activity/>Signal CSI</a><a><UserRound/>Présence</a><a><Clock3/>Historique</a><a><Settings/>Paramètres</a></div><div className="git"><Github/>WiFi Sense<small>Prototype open source</small></div></aside>
 <section className="center"><div className="radar"><div className="sweep"/><div className="line h"/><div className="line v"/><div className="ring r1"/><div className="ring r2"/><div className="ring r3"/><div className="origin"><Wifi/></div><span className="N">N</span><span className="E">E</span><span className="S">S</span><span className="O">O</span>{presence&&<div className="human" style={{left:'50%',top:'50%'}}><UserRound/><b>Humain détecté</b><small>{confidence}% de confiance</small></div>}{zones.map((z,i)=><div className="zone" key={i} style={{left:z.x+'%',top:z.y+'%'}}><span className={presence?'hot':''}/><small>{z.name}</small></div>)}</div><div className="progress"><div><span className={scan?'loader':''}/><b>{scan?'Analyse CSI en cours…':status}</b><small>Variations du canal radio analysées localement</small></div><div className="bar"><i style={{width:confidence+'%'}}/></div><span>{confidence}%</span></div><div className="cards"><div><h3>État de présence</h3><div className={'presence '+(presence?'detected':'clear')}><ShieldCheck/>{presence?'Présence probable':'Aucune présence'}<small>{presence?'Signal perturbé par un corps humain':'Canal proche du profil de pièce vide'}</small></div></div><div><h3>Signal Wi‑Fi</h3><p className="mini">Variation CSI en temps réel</p><svg className="chart" viewBox="0 0 500 120" preserveAspectRatio="none"><polyline points={graph} fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div><h3>Détection récente</h3><div className="event"><HeartPulse/><span><b>{presence?'Présence détectée':'Zone libre'}</b><em>{motion?'Mouvement en cours':'Pas de mouvement significatif'}</em></span></div></div></div></section>
 <aside className="right"><h2>Analyse de présence</h2><div className="heroStatus"><div className={'orb '+(presence?'on':'')}><UserRound/></div><strong>{status}</strong><small>{confidence}% de confiance</small></div><div className="row"><span>Présence</span><b>{presence?'OUI':'NON'}</b></div><div className="row"><span>Mouvement</span><b>{motion?'OUI':'NON'}</b></div><div className="row"><span>Type de mesure</span><b>CSI</b></div><div className="explain"><strong>Comment ça marche ?</strong><p>Le système mesure les variations du canal Wi‑Fi. Les mouvements humains modifient la propagation radio ; un algorithme peut alors estimer une présence sans caméra.</p></div><div className="warning">⚠️ Ce prototype indique une probabilité de présence, pas l'identité d'une personne.</div></aside></div><footer>WiFi Sense • présence sans caméra • traitement local</footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);